name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - 'README.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Create output folder
      run: mkdir output
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -o output/
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: assets-for-download
        path: output
